### ISSUE TITLE
Red squiggly lines everywhere

### ISSUE THREAD

**Issue by letmaik** [penev92/Oraide.LanguageServer#2]
![image](https://user-images.githubusercontent.com/530988/153775614-4898a68f-f7e9-47a2-8a5c-901546760bd1.png)

**Comment by letmaik** [comment]
This happens only when the YAML extension from Red Hat is enabled as well, which I'm using for intellisense for GitHub Actions files:

```json
    "yaml.schemas": {
        "http://json.schemastore.org/github-workflow": [
            "**/.github/workflows/*.yaml",
            "**/.github/workflows/*.yml"
        ],
        "http://json.schemastore.org/github-action": [
            "action.yaml",
            "action.yml"
        ]
    },
```

**Comment by penev92** [comment]
I have no control over the RedHat extension, nor over the indentation, which is controller by VSCode and enforced by the project's `.editorconfig` file as per project conventions.
Basically there is nothing I can help with here, sorry  🤷‍♂️

**Comment by penev92** [comment]
@letmaik as there are many ways in which OpenRA's MiniYAML is not proper/standard YAML (not just indentation) and thus I don't expect the RedHat extension would be very helpful with OpenRA, I could suggest disabling it for this workspace.
