### ISSUE TITLE
Add README and LICENSE files

### ISSUE THREAD

**Issue by letmaik** [penev92/Oraide.LanguageServer#4]
Adding those files at the top-level would be great. The README should have a few notes on what this is, and probably link to the subfolders.

**Comment by penev92** [comment]
I filed #8 for the license and tried to do the same for the readme but to my surprise the GitHub interface for it just committed 🤷‍♂️ 
I'm open to any suggestions on what to add to the README or how to format or word things better.

**Comment by letmaik** [comment]
I would add a link to OpenRA and also the MiniYAML spec, otherwise it looks good.

**Comment by penev92** [comment]
Added links to https://github.com/OpenRA/OpenRA and https://github.com/OpenRA/MiniYAML.tmbundle
Those two plus the explanation that the OpenRA internal MiniYAML parser is used is the closest we'll get to a language specification I feel.

**Comment by letmaik** [comment]
There's also https://www.openra.net/book/modding/miniyaml/index.html. I'm assuming parsing of values (lists etc.) is not a concern of the parser itself but rather down to the specific classes? The intellisense tooltips show the types but I guess they are not validated in the language server?

**Comment by penev92** [comment]
Hm, good point. Let me try and explain that a bit better in the README and then tell me if that's clear. I'll ping you when it's done.

**Comment by penev92** [comment]
@letmaik  I added the link to the Book, thanks. Also expanded the parsing section a bit.

> The intellisense tooltips show the types but I guess they are not validated in the language server?

if you mean validating values in yaml, then no, not yet. I do plan to add diagnostics (warnings and error messages) though, and that could include validating values.

Merging #8 closed this issue automatically but if you have any more suggestions on the README let me know.
